name: "Birth Github Config"
description: "Action to config Birth projects on Github"
author: "Birth Software"

outputs:
  BIRTH_GITHUB_TARGETS:
    description: "Array of Birth targets"
    value: ${{ steps.generate_config.outputs.BIRTH_GITHUB_TARGETS }}
  BIRTH_BUILD_TYPES:
    description: "Array of Birth build types"
    value: ${{ steps.generate_config.outputs.BIRTH_BUILD_TYPES }}
  BIRTH_CMAKE_BUILD_TYPES:
    description: "Array of Birth CMake build types"
    value: ${{ steps.generate_config.outputs.BIRTH_CMAKE_BUILD_TYPES }}
  BIRTH_COMPILERS:
    description: "Array of Birth compilers"
    value: ${{ steps.generate_config.outputs.BIRTH_COMPILERS }}
  BIRTH_LINUX_IMAGE:
    description: "Birth Linux image"
    value: ${{ steps.generate_config.outputs.BIRTH_LINUX_IMAGE }}
  BIRTH_MACOS_IMAGE:
    description: "Birth MacOS image"
    value: ${{ steps.generate_config.outputs.BIRTH_MACOS_IMAGE }}
  BIRTH_WINDOWS_IMAGE:
    description: "Birth Windows image"
    value: ${{ steps.generate_config.outputs.BIRTH_WINDOWS_IMAGE }}

runs:
  using: "composite"
  steps:
    - id: generate_config
      shell: bash
      run: |
        echo '["cl", "gcc", "clang", "tcc"]' > birth_compilers.json
        BIRTH_COMPILERS=$(cat birth_compilers.json)
        echo "BIRTH_COMPILERS=$BIRTH_COMPILERS" >> $GITHUB_OUTPUT

        echo '["${{env.BIRTH_LINUX_IMAGE}}", "${{env.BIRTH_MACOS_IMAGE}}", "${{env.BIRTH_WINDOWS_IMAGE}}"]' > os_list.json
        BIRTH_GITHUB_TARGETS=$(cat os_list.json)
        echo "BIRTH_GITHUB_TARGETS=$BIRTH_GITHUB_TARGETS" >> $GITHUB_OUTPUT

        echo '["MinSizeRel", "Release", "RelWithDebInfo", "Debug"]' > cmake_build_types.json
        BIRTH_CMAKE_BUILD_TYPES=$(cat cmake_build_types.json)
        echo "BIRTH_CMAKE_BUILD_TYPES=$BIRTH_CMAKE_BUILD_TYPES" >> $GITHUB_OUTPUT

        echo '["debug", "release_safe", "release_fast", "release_small" ]' > birth_build_types.json
        BIRTH_BUILD_TYPES=$(cat birth_build_types.json)
        echo "BIRTH_BUILD_TYPES=$BIRTH_BUILD_TYPES" >> $GITHUB_OUTPUT

        echo "BIRTH_LINUX_IMAGE=$BIRTH_LINUX_IMAGE" >> $GITHUB_OUTPUT
        echo "BIRTH_MACOS_IMAGE=$BIRTH_MACOS_IMAGE" >> $GITHUB_OUTPUT
        echo "BIRTH_WINDOWS_IMAGE=$BIRTH_WINDOWS_IMAGE" >> $GITHUB_OUTPUT
      env:
        BIRTH_LINUX_IMAGE: ubuntu-24.04
        BIRTH_MACOS_IMAGE: macos-15
        BIRTH_WINDOWS_IMAGE: windows-2022
