name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-config:
    runs-on: ubuntu-latest
    outputs:
      BIRTH_GITHUB_TARGETS: ${{ steps.generate-config.outputs.BIRTH_GITHUB_TARGETS }}
      BIRTH_CMAKE_BUILD_TYPES: ${{ steps.generate-config.outputs.BIRTH_CMAKE_BUILD_TYPES }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate config
        id: GENERATE-CONFIG
        uses: ./
        with:
          include_windows_aarch64: true
  receive-config:
    needs: generate-config
    strategy:
      matrix:
        os: ${{ fromJSON(needs.generate-config.outputs.BIRTH_GITHUB_TARGETS) }}
        cmake_build_type: ${{ fromJSON(needs.generate-config.outputs.BIRTH_CMAKE_BUILD_TYPES) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check
        shell: bash
        run: |
          set -ex
          echo $BIRTH_GITHUB_TARGETS
          echo ${{matrix.os}}
          echo ${{matrix.cmake_build_type}}
          uname -a
          clang -v
